# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-30 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='login_User',
        ),
    ]
